
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NAME NUMBER STRING LINE_COMMENT POINT EQ NEQ GT LT GET LET ASSIGN SUM SUBST PROD DIV LPARENT RPARENT COL SEMCOL INPUT PRINT IF ELSE WHILE CLASS AND OR NOTsumExpr  : sumExpr sumop term\n                | term\n    sumop    : SUM\n                | SUBST\n    term : term mulop opElement\n            | opElement\n    opElement    : name\n                    | number\n    mulop    : PROD\n                | DIV\n    inputStmt : INPUT LPARENT RPARENT\n    outputStmt : PRINT LPARENT STRING RPARENT\n    number : NUMBERstring : STRINGname : NAME'
    
_lr_action_items = {'NAME':([0,8,9,10,11,12,13,],[6,6,-3,-4,6,-9,-10,]),'NUMBER':([0,8,9,10,11,12,13,],[7,7,-3,-4,7,-9,-10,]),'$end':([1,2,3,4,5,6,7,14,15,],[0,-2,-6,-7,-8,-15,-13,-1,-5,]),'SUM':([1,2,3,4,5,6,7,14,15,],[9,-2,-6,-7,-8,-15,-13,-1,-5,]),'SUBST':([1,2,3,4,5,6,7,14,15,],[10,-2,-6,-7,-8,-15,-13,-1,-5,]),'PROD':([2,3,4,5,6,7,14,15,],[12,-6,-7,-8,-15,-13,12,-5,]),'DIV':([2,3,4,5,6,7,14,15,],[13,-6,-7,-8,-15,-13,13,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sumExpr':([0,],[1,]),'term':([0,8,],[2,14,]),'opElement':([0,8,11,],[3,3,15,]),'name':([0,8,11,],[4,4,4,]),'number':([0,8,11,],[5,5,5,]),'sumop':([1,],[8,]),'mulop':([2,14,],[11,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sumExpr","S'",1,None,None,None),
  ('sumExpr -> sumExpr sumop term','sumExpr',3,'p_sum_expr','pythonInterpreter.py',111),
  ('sumExpr -> term','sumExpr',1,'p_sum_expr','pythonInterpreter.py',112),
  ('sumop -> SUM','sumop',1,'p_sumop','pythonInterpreter.py',117),
  ('sumop -> SUBST','sumop',1,'p_sumop','pythonInterpreter.py',118),
  ('term -> term mulop opElement','term',3,'p_term','pythonInterpreter.py',123),
  ('term -> opElement','term',1,'p_term','pythonInterpreter.py',124),
  ('opElement -> name','opElement',1,'p_op_element','pythonInterpreter.py',129),
  ('opElement -> number','opElement',1,'p_op_element','pythonInterpreter.py',130),
  ('mulop -> PROD','mulop',1,'p_mulop','pythonInterpreter.py',135),
  ('mulop -> DIV','mulop',1,'p_mulop','pythonInterpreter.py',136),
  ('inputStmt -> INPUT LPARENT RPARENT','inputStmt',3,'p_input_stmt','pythonInterpreter.py',141),
  ('outputStmt -> PRINT LPARENT STRING RPARENT','outputStmt',4,'p_output_stmt','pythonInterpreter.py',146),
  ('number -> NUMBER','number',1,'p_number','pythonInterpreter.py',151),
  ('string -> STRING','string',1,'p_string','pythonInterpreter.py',155),
  ('name -> NAME','name',1,'p_name','pythonInterpreter.py',159),
]
